# Generated by Django 5.1.5 on 2025-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_level',
            field=models.IntegerField(default=1),
        ),
    ]
