# Generated by Django 5.1.5 on 2025-02-20 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KidVenture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprogress",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
