# Generated by Django 5.1.5 on 2025-03-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0002_activity_current_level_activity_max_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='current_level',
            new_name='max_levels',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_level',
        ),
    ]
