# Generated by Django 5.1.5 on 2025-04-01 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KidVenture", "0003_rename_current_level_activity_max_levels_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameprogress",
            name="level",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="gameprogress",
            name="mistakes",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="gameprogress",
            name="time_taken",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gameprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
