# Generated by Django 5.1.5 on 2025-01-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0004_alter_class_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='access_token',
            field=models.CharField(default='DEFAULT_TOKEN', editable=False, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
