# Generated by Django 5.1.5 on 2025-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0005_gameprogress_activity_gameprogress_is_free_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='game_type',
            field=models.CharField(choices=[('matching', 'Matching Game'), ('memory', 'Memory Game')], default='matching', max_length=20),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='game_type',
            field=models.CharField(choices=[('matching', 'Matching Game'), ('memory', 'Memory Game')], default='matching', max_length=20),
        ),
    ]
