# Generated by Django 5.1.5 on 2025-04-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0006_activity_game_type_gameprogress_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='game_type',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gameprogress',
            old_name='game_type',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
    ]
