# Generated by Django 5.1.5 on 2025-04-21 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0008_activity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, max_length=50, null=True)),
                ('max_levels', models.IntegerField(default=1)),
                ('game', models.CharField(choices=[('matching', 'Matching Game'), ('memory', 'Memory Game')], default='matching', max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to='KidVenture.class')),
            ],
        ),
    ]
