# Generated by Django 5.1.5 on 2025-04-25 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0009_remove_student_classroom_student_classrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KidVenture.class'),
            preserve_default=False,
        ),
    ]
