# Generated by Django 5.1.5 on 2025-04-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0010_remove_student_classroom_student_classrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classrooms',
            field=models.ManyToManyField(related_name='activities', to='KidVenture.class'),
        ),
    ]
