# Generated by Django 5.1.5 on 2025-04-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0011_activity_classrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='classrooms',
        ),
    ]
