# Generated by Django 5.1.5 on 2025-04-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0012_remove_activity_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='KidVenture.class'),
            preserve_default=False,
        ),
    ]
