# Generated by Django 5.1.5 on 2025-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0013_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_settings',
            field=models.JSONField(default=dict),
        ),
    ]
