# Generated by Django 5.1.5 on 2025-02-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0014_user_avatar_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_settings',
        ),
    ]
