# Generated by Django 5.1.5 on 2025-04-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0014_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
