# Generated by Django 5.1.5 on 2025-02-27 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidVenture', '0016_remove_student_classroom_class_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='KidVenture.class'),
            preserve_default=False,
        ),
    ]
